Implementação inicial do leitor de simulados
einsteinfloripa/leitor-simulados pull request #2
Opened 2023-04-26 00:05 UTC by patrickmetzner

Este PR contém a implementação inicial do leitor de simulados:
- Configurações do container Docker da aplicação;
- Modelo v0.0.0 de detecção dos macro blocos de informação nas imagens;
- Script `object_detection.py` com as funções necessárias para executar inferências com modelos TF Lite;
- Script `run_detection_model.py` para:
  - Executar inferências em imagens de cartões de resposta;
  - Renderizar detecções em imagens dos cartões de resposta;
  - Gerar arquivos JSON contendo as coordenadas e níveis de confiança das detecções em cada imagem;
  - Recortar regiões detectadas de cada imagem de cartões de resposta;

2023-04-26 10:22 UTC, vianaz reviewed
@patrickmetzner Show demais!!!! Fiz os testes aqui e já está detectando bem! Segue vídeo ilustrativo

[Screencast from 26-04-2023 07:22:02.webm](https://user-images.githubusercontent.com/97882083/234547145-766226a2-d10e-450b-a436-32d1206eae1e.webm)

2023-04-26 10:26 UTC, vianaz requested changes
@patrickmetzner um problema que encontrei foi ao tentar apagar as pastas tenho problema de permissão por questão de ser volumes que estão no root directory do container (já passei bastante por isso hahaha)

![image](https://user-images.githubusercontent.com/97882083/234547805-e0002c13-2fe2-403d-847c-d9c3d9735d9a.png)

Um *workaround* é simplesmente apagar via linha de comando usando `sudo`, mas se tiver tempo para dar uma resolvida nisso seria legal, porque não deve ser algo que tome tanto tempo

Segue links uteis que podem ajudar a lidar com isso:

https://mydeveloperplanet.com/2022/10/19/docker-files-and-volumes-permission-denied/
https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

2023-04-26 10:31 UTC, vianaz commented on Dockerfile
> +RUN python3 -m pip install --upgrade pip
Assim que subi o container fui validar e está usando uma versão bem antiga do python

![image](https://user-images.githubusercontent.com/97882083/234548958-2a188ad4-c9dc-4b78-9174-b890d545024f.png)

2023-04-26 20:08 UTC, patrickmetzner commented on Dockerfile
> +RUN python3 -m pip install --upgrade pip
Beleza!
Vou subir uma atualização com uma versão mais recente do Python!

2023-04-27 18:42 UTC, patrickmetzner commented on Dockerfile
> +RUN python3 -m pip install --upgrade pip
@vianaz atualizei o Dockerfile pra ubuntu:focal que usa Python 3.8.10 que terá suporte até 10/2024.

Tentei utilizar uma imagem Python, mas a instalação do TF Lite apresentou uns probleminhas e eu precisaria de mais tempo pra resolver.
Também tentei utilizar ubuntu:jammy que também apresentou problemas com a instalação do TF Lite.

Acredito que podemos deixar dessa forma por enquanto e depois tentamos atualizar com mais calma, mas sinta-se a vontade para tentar criar um container baseado nas imagens Python mais recentes.

2023-04-27 18:55 UTC, vianaz commented on Dockerfile
> +RUN python3 -m pip install --upgrade pip
@patrickmetzner tranquilo, a ideia era que não te tomasse muito tempo mesmo, o que tomar a gente deixa como tech debit e resolve depois, funcionando é bola pra frente, até porque isso não vai causar muito impacto por agora que estamos em MVP. resolvendo conversation.....

2023-04-27 19:13 UTC, vianaz commented on requirements.txt
Conversation sendo resolvida, para melhor entendimento segue [link explicando a razão na conversa do Slack](https://einsteinfloripa.slack.com/archives/C053972RBDJ/p1682621356195399?thread_ts=1682467691.606909&cid=C053972RBDJ)

2023-04-27 19:55 UTC, merged